Update to support JUnit report generation.

diff --git a/scripts/validate/govcms-prevent-theme-modules b/scripts/validate/govcms-prevent-theme-modules
--- a/scripts/validate/govcms-prevent-theme-modules
+++ b/scripts/validate/govcms-prevent-theme-modules
@@ -11,7 +11,11 @@ set -euo pipefail
 
 GOVCMS_PREVENT_THEME_MODULES=${GOVCMS_PREVENT_THEME_MODULES:-true}
 GOVCMS_INFO_FILE_LIST=${GOVCMS_INFO_FILE_LIST:-}
+GOVCMS_OUTFILE=${GOVCMS_OUTFILE:-govcms-validate-prevent-theme-modules}
 DRUPAL_DIR=${DRUPAL_DIR:-web}
+
+FAILURES=""
+function join_char { local IFS="$1" shift; echo "$*"; }
 
 echo "GovCMS Validate :: Scan themes for modules"
 
@@ -35,10 +39,20 @@ IFS=$'\n'
 for file in $GOVCMS_INFO_FILE_LIST; do
   if [[ $(yq r "$file" 'type') == 'module' ]]; then
     echo "[fail]: Module detected with $file"
-    exit 1;
+    FAILURES="$FAILURES,$file"
   fi
   echo "[info]: $file is valid"
 done
 
 IFS=$IFS_BAK
-echo "[success]: No modules detected."
+
+FILE_LFS=$(join_char , $GOVCMS_INFO_FILE_LIST)
+govcms-prepare-xml --failures="${FAILURES}" --total="${FILE_LFS}" --name="${GOVCMS_OUTFILE}" --fail-message="GovCMS.QA.FindModule"
+
+if [ -z "${FAILURES}" ]; then
+  echo "[success]: No modules detected."
+  exit 0
+fi
+
+echo "[fail]: Modules detected"
+exit 1
diff --git a/scripts/validate/govcms-validate-illegal-files b/scripts/validate/govcms-validate-illegal-files
--- a/scripts/validate/govcms-validate-illegal-files
+++ b/scripts/validate/govcms-validate-illegal-files
@@ -8,6 +8,10 @@ set -euo pipefail
 
 GOVCMS_ILLEGAL_FILE_PATTERN=${GOVCMS_ILLEGAL_FILE_PATTERN:-"(adminer|phpmyadmin|bigdump)"}
 GOVCMS_FILE_LIST=${GOVCMS_FILE_LIST:-}
+GOVCMS_OUTFILE=${GOVCMS_OUTFILE:-govcms-illegal-files}
+
+FAILURES=""
+function join_char { local IFS="$1" shift; echo "$*"; }
 
 function illegal_file {
   if [[ "$1" =~ $GOVCMS_ILLEGAL_FILE_PATTERN(.+)?\.php ]]; then
@@ -18,7 +22,7 @@ function illegal_file {
 
 function fail {
   echo "[fail]: Illegal file found [$1]"
-  exit 1
+  FAILURES="${FAILURES},{$1}"
 }
 
 echo "GovCMS Validate :: Illegal files"
@@ -39,5 +43,13 @@ find . -name "*.php" -print0 | while read -rd $'\0' file; do
   fi
 done
 
-echo "[success]: No illegal files."
-exit 0
+FILE_LFS=$(join_char , $GOVCMS_FILE_LIST)
+govcms-prepare-xml --failures="${FAILURES}" --total="${FILE_LFS}" --name="${GOVCMS_OUTFILE}" --fail-message="GovCMS.QA.IllegalFiles"
+
+if [ -z "${FAILURES}" ]; then
+  echo "[success]: No illegal files."
+  exit 0
+fi
+
+echo "[fail]: Illegal files detected"
+exit 1
diff --git a/scripts/validate/govcms-validate-permissions b/scripts/validate/govcms-validate-permissions
--- a/scripts/validate/govcms-validate-permissions
+++ b/scripts/validate/govcms-validate-permissions
@@ -11,6 +11,10 @@ set -euo pipefail
 
 GOVCMS_ROLE_PATTERN=${GOVCMS_ROLE_PATTERN:-user.role.*.yml}
 GOVCMS_FILE_LIST=${GOVCMS_FILE_LIST:-}
+GOVCMS_OUTFILE=${GOVCMS_OUTFILE:-govcms-validate-permissions}
+
+FAILURES=""
+function join_char { local IFS="$1" shift; echo "$*"; }
 
 echo "GovCMS Validate :: Disallowed permissions"
 
@@ -25,14 +29,26 @@ IFS=$'\n'
 for file in $GOVCMS_FILE_LIST; do
     if [ $(cat "$file" | grep -c -e "administer permissions" -e "administer modules" -e "administer software updates" -e "administer site configuration" -e "use PHP for google analytics tracking visibility" -e "import configuration") -ne 0 ]; then
       echo "[fail]: $file has restricted permissions";
-      exit 1;
+      FAILURES="$FAILURES,$file"
+      continue
     fi
     if [[ $(yq r "$file" 'is_admin') == 'true' ]]; then
       echo "[fail]: $file is listed as an admin role";
-      exit 1;
+      FAILURES="$FAILURES,$file"
+      continue
     fi
     echo "[info]: $file is valid"
 done
 
 IFS=$IFS_BAK
-echo "[success]: No elevated permissions detected in configuration."
+
+FILE_LFS=$(join_char , $GOVCMS_FILE_LIST)
+govcms-prepare-xml --failures="${FAILURES}" --total="${FILE_LFS}" --name="${GOVCMS_OUTFILE}" --fail-message="GovCMS.QA.IllegalPermissions"
+
+if [ -z "${FAILURES}" ]; then
+  echo "[success]: No elevated permissions detected in configuration."
+  exit 0
+fi
+
+echo "[fail]: Elevated permissions detected"
+exit 1
diff --git a/scripts/validate/govcms-validate-platform-yml b/scripts/validate/govcms-validate-platform-yml
--- a/scripts/validate/govcms-validate-platform-yml
+++ b/scripts/validate/govcms-validate-platform-yml
@@ -11,6 +11,10 @@ set -euo pipefail
 
 GOVCMS_PLATFORM_FILES=${GOVCMS_PLATFORM_FILES:-}
 GOVCMS_YAML_LINT=${GOVCMS_YAML_LINT:-}
+GOVCMS_OUTFILE=${GOVCMS_OUTFILE:-govcms-validate-platform}
+
+FAILURES=""
+function join_char { local IFS="$1" shift; echo "$*"; }
 
 echo "GovCMS Validate :: Yaml lint platform files"
 
@@ -31,9 +35,19 @@ IFS=$'\n'
 for file in $GOVCMS_PLATFORM_FILES; do
   if ! $GOVCMS_YAML_LINT "$file"; then
     echo "[fail]: $file failed lint";
-    exit 1;
+    FAILURES="$FAILURES,$file"
   fi
 done
 
 IFS=$IFS_BAK
-echo "[success]: No YAML issues in platform files."
+
+FILE_LFS=$(join_char , $GOVCMS_PLATFORM_FILES)
+govcms-prepare-xml --failures="${FAILURES}" --total="${FILE_LFS}" --name="${GOVCMS_OUTFILE}" --fail-message="GovCMS.QA.IllegalPermissions"
+
+if [ -z "${FAILURES}" ]; then
+  echo "[success]: No YAML issues in platform files."
+  exit 0
+fi
+
+echo "[fail]: YAML problems detected"
+exit 1
diff --git a/scripts/validate/govcms-validate-theme-yml b/scripts/validate/govcms-validate-theme-yml
--- a/scripts/validate/govcms-validate-theme-yml
+++ b/scripts/validate/govcms-validate-theme-yml
@@ -11,6 +11,10 @@ GOVCMS_THEME_FILES=${GOVCMS_THEME_FILES:-}
 GOVCMS_YAML_LINT=${GOVCMS_YAML_LINT:-}
 GOVCMS_THEME_DIR=${GOVCMS_THEME_DIR:-}
 GOVCMS_LINT_EXCLUDE_PATTERN=${GOVCMS_LINT_EXCLUDE_PATTERN:-}
+GOVCMS_OUTFILE=${GOVCMS_OUTFILE:-govcms-validate-theme-yml}
+
+FAILURES=""
+function join_char { local IFS="$1" shift; echo "$*"; }
 
 echo "GovCMS Validate :: Yaml lint theme files"
 
@@ -47,9 +51,19 @@ for file in $GOVCMS_THEME_FILES; do
 
   if ! $GOVCMS_YAML_LINT "$file"; then
     echo "[fail]: $file failed lint";
-    exit 1;
+    FAILURES="$FAILURES,$file"
   fi
 done
 
 IFS=$IFS_BAK
-echo "[success]: No YAML issues in theme files."
+
+FILE_LFS=$(join_char , $GOVCMS_THEME_FILES)
+govcms-prepare-xml --failures="${FAILURES}" --total="${FILE_LFS}" --name="${GOVCMS_OUTFILE}" --fail-message="GovCMS.QA.InvalidThemeYml"
+
+if [ -z "${FAILURES}" ]; then
+  echo "[success]: No YAML issues in theme files."
+  exit 0
+fi
+
+echo "[fail]: YAML issues in theme files."
+exit 1
